TrashTagBackend/TrashTagBackend/distributor/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired

class DistributorLoginForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class DistributorRegisterForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Register')

TrashTagBackend/TrashTagBackend/distributor/routes.py
from flask import render_template, request, Blueprint, session, redirect, url_for, flash, jsonify
from TrashTagBackend.distributor.forms import *
from TrashTagBackend.models import *
from TrashTagBackend import db, qr

distributor = Blueprint('distributor', __name__)

@distributor.route("/",methods=['GET', 'POST'])
def home():
	if(not session.get('d_uname') or not session.get('d_pass')):
		flash('Please Login to Access', 'info')
		return redirect(url_for('distributor.login', next='distributor.home'))

	dist = DistributorModel.query.filter_by(username=session['d_uname']).first()
	
	if(request.method=='POST'):
		data = request.form
		loc = LocationModel(f"Dustbin<{data['dname']}>", data['lat'], data['lng'])

		if(LocationModel.query.filter_by(lat=data['lat'], lng=data['lng']).first()):
			loc = LocationModel.query.filter_by(lat=data['lat'], lng=data['lng']).first()

		d = Dustbin(
			name=data['dname'],
			dustbin_type=data['dtype'],
			location=loc,
			distributor=dist
		)
		db.session.add(d)
		db.session.commit()
		return jsonify({'qrkey':d.dustbinkey})
	return render_template('distributor/dhome.html', title="distributor")

@distributor.route("/login", methods=['GET', 'POST'])
def login():
	form = DistributorLoginForm()
	if(form.validate_on_submit()):
		uname, pwd = form.username.data, form.password.data
		p = DistributorModel.query.filter_by(username=uname).first()

		if(not p):
			flash('Invalid Credentials', 'danger')
			return render_template('distributor/dlogin.html', title='Distributor Login', form=form)

		if(p.password == pwd):
			nxt = request.args.get('next')
			session['d_uname'] = p.username
			session['d_pass'] = p.password
			if(nxt): return redirect(url_for(nxt))
			
			return redirect(url_for('distributor.home'))
		else:
			flash('Invalid Credentials', 'danger')
			return render_template('distributor/dlogin.html', title='Distributor Login', form=form)

	return render_template('distributor/dlogin.html', title="Distributor Login", form=form)

@distributor.route('/register', methods=['GET', 'POST'])
def register():
	form = DistributorRegisterForm()
	if(form.validate_on_submit()):
		name, uname, pwd = form.name.data, form.username.data, form.password.data
		p = DistributorModel(
			name=name,
			uname=uname,
			pwd=pwd,
		)
		db.session.add(p)
		db.session.commit()
		flash('Login to Continue', 'info')
		return redirect(url_for('distributor.login'))
	return render_template('distributor/dreg.html', title="distributor Register", form=form)

@distributor.route('/logout')
def logout():
	session['d_uname'] = None
	session['d_pass'] = None
	return redirect(url_for('distributor.login'))
	

@distributor.route('/qrviewer/<qkey>')
def qrviewer(qkey):
	return render_template('distributor/qr.html', qr=qr.qrcode(qkey))

TrashTagBackend/TrashTagBackend/templates/distributor/dhome.html
{% extends 'layout.html' %}
{% block content %}
<div class="container p-5">
	<h1 class="display-1">Distributor</h1>
	<div class="d-flex">
		<a href={{url_for('distributor.logout')}} class="btn btn-danger mx-1">Logout</a>
		<button class="btn btn-success" data-toggle="modal" data-target="#newDustbinDialog">Commission New Dustbin</button>
	</div>
	
<!-- Modal -->
<div class="modal fade" id="newDustbinDialog" tabindex="-1" role="dialog" aria-labelledby="newDustbinDialogTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newDustbinDialogTitle">Commission new Dustbin</h5>
        <button type="button" class="close btn" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
			<input type="text" class="form-control" placeholder="Dustbin Name" id="dbn">
			
			<select name="dtype" id="dtyp" class="form-control mt-1">
				<option value="dry">Dry Waste</option>
				<option value="wet">Wet Waste</option>
				<option value="rec">Recyclable Waste</option>
			</select>

			<div class="d-flex mt-2">
			
				<input type="text" class="form-control" id="lat" readonly>
				<input type="text" class="form-control mx-1" id="lng" readonly>
				
			</div>

			<div class="modal-footer">
				<div class="btn-primary p-2" onclick="getLoc()">Get Location</div>
				<button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-success" onclick="commission()">Commission</button>
			</div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

{% block js %}
<script>
const getLoc = () => {
	navigator.geolocation.getCurrentPosition((pos) => {
		let lat = pos.coords.latitude
		let lng = pos.coords.longitude
		console.log(lat, lng)
		document.getElementById("lat").value = lat
		document.getElementById("lng").value = lng
	})
}

const commission = () => {
	fd = new FormData();
	fd.append('dname', document.getElementById("dbn").value)
	fd.append('dtype', document.getElementById("dtyp").value)
	fd.append('lat', document.getElementById("lat").value)
	fd.append('lng', document.getElementById("lng").value)
	fetch(window.location.href, {
		method:'POST',
		body: fd
	}).then((res)=>res.json()).then((res)=>{
		newloc = window.location.href + `qrviewer/${res.qrkey}`
		console.log(newloc)
		window.location.href = (newloc);
	})
}
</script>
{% endblock js %}

TrashTagBackend/TrashTagBackend/templates/distributor/dlogin.html
{% extends 'layout.html' %}
{% block content %}
<div class="container p-5">
	<h1 class="display-1">Distributor Login</h1>
	<form action="" method="post">
		{{ form.hidden_tag() }}
		<fieldset>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}
				{{ form.username(class="form-control form-control-lg") }}
			</div>
			<br>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{{ form.password(class="form-control form-control-lg") }}
			</div>
			<br>
		</fieldset>
		<br>
		<div class="form-group">
			{{ form.submit(class="btn btn-success btn-lg px-5") }}
		</div><br><br>
		<a href="{{url_for('distributor.register')}}" class="text-secondary text-decoration-none">Do not have a Distributor Account? Register</a>
	</form>
</div>
{% endblock content %}

TrashTagBackend/TrashTagBackend/templates/distributor/dreg.html
{% extends 'layout.html' %}
{% block content %}
<div class="container p-5">
	<h1 class="display-1">Distributor Register</h1>
	<form action="" method="post">
		{{ form.hidden_tag() }}
		<fieldset>
			<div class="form-group">
				{{ form.name.label(class="form-control-label") }}
				{{ form.name(class="form-control form-control-lg") }}
			</div>
			<br>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}
				{{ form.username(class="form-control form-control-lg") }}
			</div>
			<br>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{{ form.password(class="form-control form-control-lg") }}
			</div>
			<br>
		</fieldset>
		<br>
		<div class="form-group">
			{{ form.submit(class="btn btn-success btn-lg px-5") }}
		</div>
		<br><br>
		<a href="{{url_for('distributor.login')}}" class="text-secondary text-decoration-none">Already have a Distributor Account? Login</a>
	</form>
</div>
{% endblock content %}

TrashTagBackend/TrashTagBackend/templates/distributor/qr.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
<h1 class="display-1">QR Viewer</h1>
<div class="qrbox">
	<h4 class="text-success">Add this QR Code on your Dustbin</h4><br>
	<img src="{{qr}}" id="qr">
	<br><br>
</div>
</div>

{% endblock content %}