TrashTagBackend/TrashTagBackend/producer/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired

class ProducerLoginForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class ProducerRegisterForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Register')

TrashTagBackend/TrashTagBackend/producer/routes.py
from flask import render_template, request, Blueprint, session, redirect, url_for, flash, jsonify
from TrashTagBackend.producer.forms import *
from TrashTagBackend.models import *
from TrashTagBackend import db, qr
producer = Blueprint('producer', __name__)

@producer.route("/" ,methods=['GET', 'POST'])
def home():
	if(not session.get('p_uname') or not session.get('p_pass')):
		flash('Please Login to Access Page	', 'info')
		return redirect(url_for('producer.login', next='producer.home'))

	prod = ProducerModel.query.filter_by(username=session['p_uname']).first()
	
	if(request.method=='POST'):
		data = request.form
		p = Product(
			name=data['pname'],
			isbiodegradable= (data['biodegradable'] == 'b'),
			producer=prod,
			waste_type=data['wtype']
		)
		db.session.add(p)
		db.session.commit()
		return jsonify({'qrkey':p.productkey})

	return render_template('producer/phome.html', title="Producer")

@producer.route("/login", methods=['GET', 'POST'])
def login():
	if(session.get('p_pass')): return redirect(url_for('producer.home'))
	form = ProducerLoginForm()
	if(form.validate_on_submit()):
		uname, pwd = form.username.data, form.password.data
		p = ProducerModel.query.filter_by(username=uname).first()

		if(not p):
			flash('Invalid Credentials', 'danger')
			return render_template('producer/plogin.html', title='Producer Login', form=form)

		if(p.password == pwd):
			session['p_uname'] = p.username
			session['p_pass'] = p.password
			nxt = request.args.get('next')
			if(nxt): return redirect(url_for(nxt))
			return redirect(url_for('producer.home'))
		else:
			flash('Invalid Credentials', 'danger')
			return render_template('producer/plogin.html', title='Producer Login', form=form)

	return render_template('producer/plogin.html', title="Producer Login", form=form)

@producer.route('/register', methods=['GET', 'POST'])
def register():
	form = ProducerRegisterForm()
	if(form.validate_on_submit()):
		name, uname, pwd = form.name.data, form.username.data, form.password.data
		p = ProducerModel(
			name=name,
			uname=uname,
			pwd=pwd,
		)
		db.session.add(p)
		db.session.commit()
		flash('Login to Continue', 'info')
		return redirect(url_for('producer.login'))
	return render_template('producer/preg.html', title="Producer Register", form=form)

@producer.route('/logout')
def logout():
	session['p_uname'] = None
	session['p_pass'] = None
	return redirect(url_for('producer.login'))
	
@producer.route('/qrviewer/<qkey>')
def qrviewer(qkey):
	return render_template('producer/qr.html', qr=qr.qrcode(qkey))

TrashTagBackend/TrashTagBackend/templates/producer/phome.html
{% extends 'layout.html' %}
{% block content %}
<div class="container p-5">
	<h1 class="display-1">Producer</h1>
	<div class="d-flex">
		<a href={{url_for('producer.logout')}} class="btn btn-danger mx-1">Logout</a>
		<button class="btn btn-success" data-toggle="modal" data-target="#newProductDialog">Commission New Product</button>
	</div>
	
<!-- Modal -->
<div class="modal fade" id="newProductDialog" tabindex="-1" role="dialog" aria-labelledby="newProductDialogTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newProductDialogTitle">Commission new Dustbin</h5>
        <button type="button" class="close btn" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
			<input type="text" class="form-control" placeholder="Product Name" id="pn">
			
			<select name="dtype" id="biod" class="form-control mt-1">
				<option value="b">Biodegradable</option>
				<option value="nb">Non-Biodegradable</option>
			</select>

			<select name="dtype" id="wtype" class="form-control mt-1">
				<option value="wet">Wet</option>
				<option value="dry">Dry</option>
				<option value="rec">Recyclable</option>
			</select>

			<div class="modal-footer">
				
				<button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-success" onclick="commission()">Commission</button>
			</div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

{% block js %}
<script>
const commission = () => {
	fd = new FormData();
	fd.append('pname', document.getElementById("pn").value)
	fd.append('wtype', document.getElementById("wtype").value)
	fd.append('biodegradable', document.getElementById("biod").value)
	fetch(window.location.href, {
		method:'POST',
		body: fd
	}).then((res)=>res.json()).then((res)=>{
		newloc = window.location.href + `qrviewer/${res.qrkey}`
		console.log(newloc)
		window.location.href = (newloc);
	})
}
</script>
{% endblock js %}

TrashTagBackend/TrashTagBackend/templates/producer/plogin.html
{% extends 'layout.html' %}
{% block content %}
<div class="container p-5">
	<h1 class="display-1">Producer Login</h1>
	<form action="" method="post">
		{{ form.hidden_tag() }}
		<fieldset>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}
				{{ form.username(class="form-control form-control-lg") }}
			</div>
			<br>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{{ form.password(class="form-control form-control-lg") }}
				
			</div>
			<br>
		</fieldset>
		<br>
		<div class="form-group">
			{{ form.submit(class="btn btn-success btn-lg px-5") }}
		</div>
		<br><br>
		<a href="{{url_for('producer.register')}}" class="text-secondary text-decoration-none">Do not have a Producer Account? Register</a>
	</form>
</div>
{% endblock content %}

TrashTagBackend/TrashTagBackend/templates/producer/preg.html
{% extends 'layout.html' %}
{% block content %}
<div class="container p-5">
	<h1 class="display-1">Producer Register</h1>
	<form action="" method="post">
		{{ form.hidden_tag() }}
		<fieldset>
			<div class="form-group">
				{{ form.name.label(class="form-control-label") }}
				{{ form.name(class="form-control form-control-lg") }}
			</div>
			<br>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}
				{{ form.username(class="form-control form-control-lg") }}
			</div>
			<br>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{{ form.password(class="form-control form-control-lg") }}
			</div>
			<br>
		</fieldset>
		<br>
		<div class="form-group">
			{{ form.submit(class="btn btn-success btn-lg px-5") }}
		</div>
		<br><br>
		<a href="{{url_for('producer.login')}}" class="text-secondary text-decoration-none">Already Have a Producer Account? Log in</a>
	</form>
</div>
{% endblock content %}

TrashTagBackend/TrashTagBackend/templates/producer/qr.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
<h1 class="display-1">QR Viewer</h1>
<div class="qrbox">
	<h4 class="text-success">Add this QR Code on all of your Products</h4><br>
	<img src="{{qr}}" id="qr">
	<br><br>
</div>
</div>

{% endblock content %}